### ISSUE TITLE
memcache_text.cc response_get_multi() always prints a CAS of 0

### ISSUE THREAD

**Issue by astro** [etolabo/kumofs#2]
Just a minor nitpick for completeness' sake, so that nobody who uses the GETS command has to worry.

I myself use the memcached binary protocol, I am therefore not affected.

**Comment by frsyuki** [comment]
Thank you for your report. I've fixed the problem.

**Comment by astro** [comment]
Right, it's commit 4b4ad6fcbb00a95b7d0a
