### ISSUE TITLE
kumo-manager: auto-attach feature?

### ISSUE THREAD

**Issue by astro** [etolabo/kumofs#3]
Because our system is quite loaded until we scale horizontally, we prevent buffer overgrowth with ulimit -v. Whenever a killed kumo-server is being restarted, kumo-manager regards it as a "not attached node".

Would it be possible to have kumo-manager automatically attach newly connected servers?

**Comment by frsyuki** [comment]
"--auto-replace" option of kumo-manager enables that.
e.g. kumo-manager --auto-replace -v -l 192.168.10.1

**Comment by astro** [comment]
Thanks!
