### ISSUE TITLE
only 1st kumo-server in a cluster gets GET requests

### ISSUE THREAD

**Issue by astro** [etolabo/kumofs#6]
We expanded our cluster from 1 to 4 machines. Now only the 1st gets GET requests, while all see equally distributed SET traffic. Even if I GET a key that kumohash says must reside on the other three servers the 1st server receives the request.

**Comment by frsyuki** [comment]
It seems that replacing was failed (servers's log shows "replace copy failed"). Please try to run following commands:
$ kumostat -m mgr hscheck  # I think it shows "false"
$ kumoctl mgr replace
$ kumostat -m mgr hscheck  # After replacing finished, it should become "true"

**Comment by frsyuki** [comment]
Kumofs uses two routing table for dynamic rebalancing. One is named rhs (read hash space), the other one is named rhs (write hash space). When number of servers is changed (and kumoctl commands to 'attach' or 'detach'), kumo-manager updates the whs first (Set requests are distributed), and then updates rhs after replacing is finished on all kumo-servers (Get requests are also distributed).
If one or more kumo-servers failed to move data, the replacing is stopped and whs and rhs are left different. 'kumostat -m mgr hscheck' checks the difference.

**Comment by astro** [comment]
Thank you very much for this explanation! Do you keep kumofs.sf.net somewhere in git? I can help you maintain the documentation there.

Even with explicit "kumoctl replace" the hscheck never turns true here. I can see no related info in the kumo-manager logs. I probably need to dig deeper.

This is probably helpful to you:

<pre>
kumo@storage1:~$ ./kumofs/bin/kumostat -m localhost  rhs
172.21.3.233:19800:  hash space timestamp:
  Sat May 22 11:18:06 +0000 2010 clock 195474
node:
  172.21.3.233:19800  (active)
  172.21.3.231:19800  (fault)
172.21.3.232:19800:  hash space timestamp:
  Sat May 22 11:18:06 +0000 2010 clock 195474
node:
  172.21.3.233:19800  (active)
  172.21.3.231:19800  (fault)
172.21.3.222:19800:  hash space timestamp:
  Sat May 22 11:18:06 +0000 2010 clock 195474
node:
  172.21.3.233:19800  (active)
  172.21.3.231:19800  (fault)
172.21.3.231:19800:  hash space timestamp:
  Sat May 22 11:18:06 +0000 2010 clock 195474
node:
  172.21.3.233:19800  (active)
  172.21.3.231:19800  (fault)
</pre>

**Comment by astro** [comment]
Okay, after restarting kumo-server for a couple of time the hash space seems balanced now. Pointers still welcome.
